# This is a basic workflow to help you get started with Actions

name: Cake Fairy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run Python script
        run: python cakefairy.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Automated update $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.CAKE_TOKEN }}
